[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", default-features = false,features = ["blocking", "cookies", "rustls-tls"] }
md5 = "0.7"
